### ISSUE TITLE
Code in Pytorch 

### ISSUE THREAD

**Issue by kanzaali** [remega/Compressd_Domain_SaliencyPrediction#3]
Hi @remega,

I really learned a lot from this paper "Learning to detect Video Saliency with HEVC Features". I also want to work on motion vectors for compressed videos. Isn't your code in Pytorch? I want to replicate your code to understand more motion vectors, bit allocation, and splitting depth.

**Comment by kanza-ali** [comment]
I want to run your code, I have installed Matlab but I dont have visual studio. I am using Linux operating system.

**Comment by kanzaali** [comment]
Kindly guide me how  to run this project in Matlab and Visual studio.

**Comment by remega** [comment]
Thank you for attention. Unfortunately, it is a non deep learning work, which has been done several years ago. We accomplished it in matlab and C++ with no learning platform.

**Comment by remega** [comment]
Can you follow the instruction of this project and tell me which step is not working?

**Comment by kanzaali** [comment]
This main.m file should be run on matlab?

**Comment by remega** [comment]
Yep

**Comment by kanza-ali** [comment]
OK Thank you so much for your reply and help. 

First step is to encode the video 
Transform the video to YUV format (if not). Run trans2yuv.bat.

gives me this error 
>> run trans2yuv.bat
Error using run (line 66)
trans2yuv.bat not found.

**Comment by kanzaali** [comment]
OK Thank you so much for your reply and help.

For encoding video we can use any one of the method 

1. HM16.0 (HEVC)
2. ffmpeg (X265)

I have ffmpeg version 4.0.2

run x265encode.bat
Error using run (line 66)
x265encode.bat not found.

**Comment by remega** [comment]
The .bat script shoud run in a dos (windows) system, by double clicking the .bat file. If you would like to run in Linux, you should rewrite it by bash. BTW, this project has been only verified in window. So it may be some other issues runnung in Linux.

**Comment by kanzaali** [comment]
OK thank you so much for your response!
